rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
env:
  - "TASK=test:core"
  - "TASK=test:rails RAILS=1"
script: "bundle exec rake $TASK"
notifications:
  email: false
  irc:
    - "irc.freenode.org#camping"
